name: Deploy
'on':
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: npm --prefix functions ci
      - name: Run test
        run: npm --prefix functions test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: npm --prefix functions ci
      - name: Run lint
        run: npm --prefix functions run lint
  deploy-hosting:
    name: Deploy to Firebase Hosting
    needs: [test, lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - id: activitypub-firebase
            key: FIREBASE_SERVICE_ACCOUNT_ACTIVITYPUB_FIREBASE
          - id: activitypub-firebase-dev
            key: FIREBASE_SERVICE_ACCOUNT_ACTIVITYPUB_FIREBASE_DEV
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{secrets.GITHUB_TOKEN}}'
          firebaseServiceAccount: '${{secrets[matrix.project.key]}}'
          channelId: live
          projectId: '${{matrix.project.id}}'
  deploy-firebase:
    name: Deploy to Firebase except for Hosting
    needs: [test, lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - id: activitypub-firebase
            key: FIREBASE_SERVICE_ACCOUNT_ACTIVITYPUB_FIREBASE
          - id: activitypub-firebase-dev
            key: FIREBASE_SERVICE_ACCOUNT_ACTIVITYPUB_FIREBASE_DEV
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm --prefix functions ci
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,firestore
        env:
          GCP_SA_KEY: '${{secrets[matrix.project.key]}}'
          PROJECT_ID: '${{matrix.project.id}}'